name: Scheduled Production Tests

on:
  schedule:
    # Runs every day at 9:00 AM UTC (adjust as needed)
    - cron: '0 9 * * *'
  workflow_dispatch: # Allows manual trigger from GitHub UI

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'lts/*'
        
    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
<<<<<<< Updated upstream
      
    - name: Run Tests
        env:
          baseUrl: 'https://automationexercise.com/'
          email: ${{ secrets.email }}
          password: ${{ secrets.password }}
        run: npm test
=======

    - name: Run UI Tests
      env:
        baseUrl: 'https://automationexercise.com/'
        email: ${{ secrets.email }}
        password: ${{ secrets.password }}
      run: npm test
>>>>>>> Stashed changes
      
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
        
    - name: Upload test artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: test-results/
        retention-days: 30